//
// Created by miriam on 11/03/23.
//

#ifndef AGENDAPROGRAMMAZIONE_BOARDCONTROLLER_H
#define AGENDAPROGRAMMAZIONE_BOARDCONTROLLER_H


class BoardController {

};


#endif //AGENDAPROGRAMMAZIONE_BOARDCONTROLLER_H
